Migrate to web streams
BonnierNews/atlas-html-stream pull request #3
Opened 2023-03-20 14:10 UTC by acme

This change migrates from the Node.js stream API to the WHATWG Web Streams API, which Node.js also supports.

2023-03-20 14:29 UTC, JakeChampion approved these changes
Nice work!
I thought I would note that this is a breaking change due to the fact that the package now relies on a minimum NodeJS version of 18.0.0 due to the use of the `TransformStream` web-stream class being used. If this patch is accepted, the major version of the package should be bumped to indicate this breaking change as per Semantic Versioning rules.

2023-03-21 12:22 UTC, markusn requested changes
the github workflow needs to be updated to run on >=18 if that is required

2023-03-21 15:55 UTC, jonaswalden reviewed
Cool!

2023-03-21 15:55 UTC, jonaswalden commented on test/HtmlParser.test.js
> +  }
May I suggest that we just store the chunks as they are passed? After all we're testing the output of the parser, not the output of this serializer. 

Also this might not catch bugs where the parser incorrectly identifies a piece of HTML as a text node. The chunks passed could be `[ { text: "<a>" } ]` instead of `[ { name: "a", data: {} } ]` but the serialized output would still be `<a>`.

```js
  class TinyController {
    constructor() {
      this.queue = [];
    }
    enqueue(chunk) {
     this.queue.push(chunk);
    }
    reset() {
      this.queue.length = 0;
    }
  }

 const parser = new HtmlParser();
 const tinyController = new TinyController();
 parser.transform("<a>", tinyController);
 expect(tinyController.queue.length).to.equal(1);
 expect(tinyController.queue).to.deep.equal([{ name: "a", data: {} }]);
```

2023-03-21 15:55 UTC, jonaswalden commented on src/HtmlParser.js
> +module.exports = class HtmlParser {
Why do we no longer extend a transform stream interface?

2023-03-23 10:00 UTC, acme commented on test/HtmlParser.test.js
> +  }
Thanks. I implemented this in https://github.com/BonnierNews/atlas-html-stream/pull/3/commits/46bf4303670ce2ce242d58985b6a15ea18991451.

2023-03-23 10:26 UTC, acme commented on src/HtmlParser.js
> +module.exports = class HtmlParser {
The `Transform` class is part of the [Node.js stream API](https://nodejs.org/api/stream.html#class-streamtransform), which this change is migrating away from.

2023-03-23 10:32 UTC, jonaswalden commented on src/HtmlParser.js
> +module.exports = class HtmlParser {
Can't we extend the web stream `TransformStream` class? 
Either we could be explicit and import `TransformStream` from `node:streams/web` or just extend the global class. As of Node 18 the global refers to the web stream interface.

https://nodejs.org/docs/latest-v18.x/api/webstreams.html#class-transformstream

2023-03-23 10:35 UTC, markusn commented on src/HtmlParser.js
> +module.exports = class HtmlParser {
Importing from node:streams/web isn't an option if we should be able to run it from another runtime than node. If it is already in the global scope in 18 it should be fine to just extend it without importing (as we bump the requirement to 18 anyways).

2023-03-23 11:59 UTC, jonaswalden commented on src/HtmlParser.js
> +module.exports = class HtmlParser {
> Importing from node:streams/web isn't an option if we should be able to run it from another runtime than node

ah, right! 

> If it is already in the global scope in 18…

👍

2023-03-24 12:23 UTC, markusn commented on src/HtmlParser.js
> +module.exports = class HtmlParser {
@acme see the above comments

2023-03-24 14:58 UTC, acme commented on src/HtmlParser.js
> +module.exports = class HtmlParser {
Thanks. I'm currently working on local-esi and then I'll revisit this.

2023-03-24 15:52 UTC, JakeChampion commented on src/HtmlParser.js
> +module.exports = class HtmlParser {
```suggestion
module.exports = class HtmlParser extends TransformStream {
```

2023-10-06 08:29 UTC, markusn commented
Superseeded by https://github.com/BonnierNews/atlas-html-stream/pull/4

2023-10-06 08:29 UTC, closed without merging